### ISSUE TITLE
PR #101 changed semantics and introduced memory bugs

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#105]
As my comments in that PR were not honored. Here is another try:
[lines 245 ff](/andlaus/ewoms/blob/99f281484667c858e1a8137773c12347eff6723d/ebos/collecttoiorank.hh#L245-L248) seem to be a buggy change of semantics. Note that only interior entities were pushed previously (resulting in a map of entity index (by traversal) to interior entity index (by traversal). The size of localIndexMap_ is never set.

```
(gdb)
#0  Ewoms::CollectDataToIORank<Ewoms::EclCpGridManager<Ewoms::Properties::TTag::EclFlowProblem> >::CollectDataToIORank (this=0x1bad038, gridManager=...)
    at /home/mblatt/src/dune/opm/ewoms/ebos/collecttoiorank.hh:247
247                             localIndexMap_[elemIdx] = elemIdx;
(gdb) p elemIdx
$5 = 1
(gdb) p localIndexMap_
$6 = std::vector of length 0, capacity 165
(gdb) 
```

**Comment by andlaus** [comment]
do mind opening a PR reversing the `localIndexMap_` parts of #101?

**Comment by blattms** [comment]
Will do that in due time.

**Comment by andlaus** [comment]
what's the status here? @blattms: do you intend to fix this?
