### ISSUE TITLE
Segfault with current master.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/ewoms#14]
Program received signal SIGSEGV, Segmentation fault.
beginIterationPostProcess (this=0xfd0240)
    at /home/robertk/work/OPM/release/ewoms/applications/ebos/eclpeacemanwell.hh:944
944             actualBottomHolePressure_ = dofVariables_.begin()->second.pressure[0];

The test case was spe9.

**Comment by andlaus** [comment]
weird, on my machine it works fine, even valgrind and ASAN do not complain (in debug mode, optimized mode produces some strange errors which I'm currently investigating). could you provide a backtrace?

but the error looks like you have removed or deactivated all connections of a well in the deck, but not the well itself. (which does not make any sense, but should not crash the simulation.) did you modify the SPE9 deck?

**Comment by andlaus** [comment]
as far as I can remember, this has been fixed a while ago. if that is not the case, please reopen...
