### ISSUE TITLE
test generation seems bogus

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#148]
When I build ewoms with duncontrol and BUILDDIR=opm-parallel-dbg I see weired test generation messages:
```
...
[ 70%] [ 70%] Generating opm-seq/opm-seq/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/tests/referencesolutions/obstacle_immiscible-heuristix.vtu
Generating opm-seq/opm-seq/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/tests/referencesolutions/finger_immiscible_ecfv-heuristix.vtu
...
```
BTW there is another build directory opm-seq lying around.

**Comment by andlaus** [comment]
seems like a clash between the OPM and dune cmake build systems. @akva2: can you have a look?

**Comment by akva2** [comment]
sure, but not today

**Comment by andlaus** [comment]
is this still relevant?

**Comment by andlaus** [comment]
since silence is golden, I suppose that this can be closed ;)

**Comment by blattms** [comment]
The issue is still there:
```
Generating opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/tests/referencesolutions/powerinjection_forchheimer-heuristix.vtp
Generating opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/opm-parallel-dbg/tests/referencesolutions/powerinjection_darcy-heuristix.vtp
```

Are you by any chance using some CMake file globbing that also finds stuff in  build directories like `ewoms/opm-parallel-dbg` and treats them as source file?

**Comment by andlaus** [comment]
globbing is used, but only to specify the list of source files and the data/reference solutions to be copied to the build directory, but not to specify any source code in the eWoms build directory. the issue of yours looks to be related to the reference solutions for the tests? (I have a hard time reproducing it, though.)

**Comment by blattms** [comment]
> (I have a hard time reproducing it, though.) 

that should be quite easy:
```
mkdir ewoms/build && cd ewoms/build
cmake . && make tests#
find . -name s0004-p0001-obstacle_immiscible-heuristix.vtu
#
# output:
# ./tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu
#
mkdir ../build2 && cd ../build2
cmake . && make tests#
find . -name s0004-p0001-obstacle_immiscible-heuristix.vtu
# output:
#
# ./tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu
# ./opm-parallel-dbg/tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu
# ./opm-parallel-dbg/opm-parallel-dbg/tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu
#
cd ../build
#
# output:
#
#./tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu
# ./opm-parallel-dbg/tests/referencesolutions/s0004-p0001-obstacle_immiscible-heuristix.vtu

```

The second call even creates files in another build directory!

BTW: why are there multiple dgf files with the same name and conent?
E.g. tests/data/test_stokes2c.dgf data/test_stokes2c.dgf
