### ISSUE TITLE
Cached intensive quantities need to be available on all elements.

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#163]
I am assuming here that there is no way to get these quantities outside of the interior region. If that is wrong, please tell me how to get them there.

As pointed out in #158 everything else is a *big* surprise. Apparently, even to people that were involved with frankenstein during his resurrection.

Some occurences found are [BlackoilModelEbos.hpp:671](/OPM/opm-simulators/blob/0b0ef7e20fb0d2e406a2a6bae74d80b3b017bcec/opm/autodiff/BlackoilModelEbos.hpp#L671), [BlackoilModelEbos.hpp:888](/OPM/opm-simulators/blob/0b0ef7e20fb0d2e406a2a6bae74d80b3b017bcec/opm/autodiff/BlackoilModelEbos.hpp#L888). Yes they can be circumvented by code like @andlaus proposed, but it is only a matter of time until similar code will be produced by others.

Unfortunately, code assuming cachedIntensiveQuantities being available unconditionally is also used in StandardWellsDense_impl.hpp. Our current decomposition approach is constructed such that all local wells only perforate interior elements. But there is the plan to allow a well being split between different processes. In that case there will be perforations also into the overlap/ghost partitions and judging from the code in [StandardWellsDense_impl.hpp:189](/OPM/opm-simulators/blob/0b0ef7e20fb0d2e406a2a6bae74d80b3b017bcec/opm/autodiff/StandardWellsDense_impl.hpp#L189) and [StandardWellsDense_impl.hpp:265](/OPM/opm-simulators/blob/0b0ef7e20fb0d2e406a2a6bae74d80b3b017bcec/opm/autodiff/StandardWellsDense_impl.hpp#L265) we will need to access the intensive quantities there also.

**Comment by andlaus** [comment]
> I am assuming here that there is no way to get these quantities outside of the interior region. If that is wrong, please tell me how to get them there.

The usual answer: if you really need these quantities for non-interior entities, use element contexts and everything should work out of the box. ;) (the IQ-cache obviously won't be updated for entities that only concern non-interior elements if you only process interior elements in the loop over the grid, which is the case in most instances including linearization.)

**Comment by blattms** [comment]
Didn't you say that using using element contexts produces performance regressions?

**Comment by blattms** [comment]
I am not smart enough for such a short answer and would like to learn. Would you please elaborate a bit how you would refactor StandardWellsDense to work on elements instead of simple indices? I guess that would be needed, right?

**Comment by andlaus** [comment]
> Didn't you say that using using element contexts produces performance regressions?

Maybe someone said, but *I* didn't. (Also I'd be surprised if that was the case for element centered FV methods: Then either the grid implementation is very slow when looping over the grid or copying the IQ for the central element would be very expensive. I'll bet a beer that the latter is not the case because the main expense is reading the memory of the global IQ cache for the element. That's the same for both approaches.)

> Would you please elaborate a bit how you would refactor StandardWellsDense to work on elements instead of simple indices?

not at all (for now)? didn't you go great lengths so that wells are not distributed over several grid partitions, i.e., all IQs needed by wells are guaranteed to be for interior elements?

**Comment by andlaus** [comment]
ah: maybe you mean the statement about using `elemCtx.updateAll(elem)`? while this is pretty convenient, its indeed slower than the more-verbose code that's currently used by e.g., the FIP code of `flow_ebos`. Nevertheless, the element context approach is not necessarily slower than hard-coding the presence and "up-to-dateness" of the IQ-cache.

**Comment by blattms** [comment]
> ah: maybe you mean the statement about using elemCtx.updateAll(elem)`?

Yes I mean that. The FIP code only uses interior elements and there cachedIntensiveQuantities is available, of course. But we are talking about the ghost/overlap elements where I assumed only `elemCtx.updateAll(elem)` does work. But maybe I am wrong? Is there another way?

**Comment by blattms** [comment]
I get more confused with every answer I get.

> I'll bet a beer that the latter is not the case because the main expense is reading the memory of the global IQ cache for the element

How can they be read from a cache for ghost/overlap elements if only the interior elements were visited and cached during the linearization.

Are you saying that 
```
elemCtx.updateAll(elem);
const auto& intQuants = elemCtx.intensiveQuantities(0, 0);
```
and
```
elemCtx.updatePrimaryStencil(elem);
elemCtx.updatePrimaryIntensiveQuantities(/*timeIdx=*/0);
const auto& intQuants = elemCtx.intensiveQuantities(/*spaceIdx=*/0, /*timeIdx=*/0);
```
are doing the same for interior elements?

**Comment by blattms** [comment]
I guess you are as confused by me as I am/was by you. Will carify in  a minute.

**Comment by blattms** [comment]
I was a bit confused by all these quantities.

The problem that your fellow faced and are still facing, is that cacheIntensiveQuantities returns null pointers for non-interior elements, yet it seemed the only advertised way to get these quantities and you either never really showed the optimal way to do this otherwise (or I have missed this.

Looking at all this discussions I conclude that the optimal(?) way to get these for non-interior elements is
```
elemCtx.updatePrimaryStencil(elem);
elemCtx.updatePrimaryIntensiveQuantities(/*timeIdx=*/0);
const auto& intQuants = elemCtx.intensiveQuantities(/*spaceIdx=*/0, /*timeIdx=*/0);
```
but for interior elements the cache is a lot faster.

My problem with this semantical difference is that people have to be aware of this and I fear that will not be. The solution seems to be to provide a method `std::unique_ptr<IntensiveQuantities> intensiveQuantities( int cellIdx, int timeIdx)` to the mode. This  would use the cached values with a dummy deleter if available and otherwise uses the element context to create them.

If this would then be used consistently throughout opm-simulators, we could prevent a lot of trouble. One might even stop to expose cachedIntensiveQuantities to force people to use a more safe way...

Does that sound reasonable and feasible?

**Comment by blattms** [comment]
I would even volunteer to add that method.

**Comment by blattms** [comment]
Well, we need to create the elementContext too. So 
```c++
std::unique_ptr<IntensiveQuantities> intensiveQuantities(Simulator ebosSimulator,
                                           Element elem,
                                           int globalSpaceIndex, int timeIdx){
  Dune::MultipleCodimMultipleGeomTypeMapper<GridView,
                                        Dune::MCMGElementLayout> 
    mapper(ebosSimulator.grid().leafView());
  auto idx = mapper.map(element);
  auto* iq = ebosSimulator.model().cachedIntensiveQuantities(cell_index, /*timeIdx=*/ 0));
  if(iq)
    return unique_ptr(iq, [](auto*){});
  ElementContext elemCtx(ebosSimulator)
  elemCtx.updatePrimaryStencil(elem);
  elemCtx.updatePrimaryIntensiveQuantities(/*timeIdx=*/0);
  return elemCtx.intensiveQuantsPtr();
}
```
should do what we want if `elemCtx.intensiveQuantsPtr(` returns a unique_ptr.

**Comment by andlaus** [comment]
>>  I'll bet a beer that the latter is not the case because the main expense is reading the memory of the global IQ cache for the element
>
> How can they be read from a cache for ghost/overlap elements if only the interior elements were visited and cached during the linearization.

they are not, that's the point: if the cache does not contain them yet, they are computed from scratch and the cache is updated. On the other hand if the cache is "hot" the IQs in the element context are copied from the cache. My point was that that copying is not (much) slower than accessing it directly via the pointer provided by the cache because the "memory wall" is hit either way?



> Are you saying that
>
```
elemCtx.updateAll(elem);
const auto& intQuants = elemCtx.intensiveQuantities(0, 0);
```
>and
>
```
elemCtx.updatePrimaryStencil(elem);
elemCtx.updatePrimaryIntensiveQuantities(/*timeIdx=*/0);
const auto& intQuants = elemCtx.intensiveQuantities(/*spaceIdx=*/0, /*timeIdx=*/0);
```
>are doing the same for interior elements?

no. the first variant updates the intensive and extensive quantities of *all* DOFs which are affected by the element (including neighbors), the second only updates the stencil and the IQs (*not* the EQs!) of the "primary" DOFs (i.e., the element itself in this case). The second snipped is more verbose while doing less but it should be sufficient because you only need the IQs that are associated with the element!?

> The problem that your fellow developers faced and are still facing, is that cachedIntensiveQuantities returns null pointers for non-interior elements,

yes, it returns null pointers for "cold" entries. but it is better to crash with a bang than to silently produce subtly wrong results. don't you agree?

> but for interior elements the cache is a lot faster.

is it? I'd be interested in numbers because I've never measured this. if this was the case, then the element context could store pointers to the cache. Also, how much of the runtime could be saved by this? (I measured that the total IQ stuff was about 15% of the total runtime of the simulator for SPE9. maybe things changed...)

> My problem with this semantical difference is that people have to be aware of this and I fear that will not be the case.

yeah, sorry: the IQ cache was always conceptualized to be an internal implementation detail by me. maybe it was a mistake to use it directly for the prototype. (it saved a few days/weeks to implement it.)

**Comment by blattms** [comment]
> yes, it returns null pointers for "cold" entries. but it is better to crash with a bang than to silently produce subtly wrong results. don't you agree?

Yes, I agree. But the code I have seen does something like:
```
const auto& intQuants = *(ebosSimulator_.model().cachedIntensiveQuantities(cell_idx, /*timeIdx=*/0));
```

That is not exactly crashing with a bang. It just might segfault
somewhere very unexpected... But it is a programming error of the user
of course.

> 
> > but for interior elements the cache is a lot faster.
> 
> is it? I'd be interested in numbers because I've never measured
> this.

See /OPM/opm-simulators#1111. No beer for me, unfortunately.

**Comment by andlaus** [comment]
> That is not exactly crashing with a bang. It just might segfault somewhere very unexpected... But it is a programming error of the user of course.

I agree. count this atrocity into the "this-is-a-hack-to-save-a-few-minutes-but-in-retrospect-it-was-a-mistake" department ;)

> See /OPM/opm-simulators#1111. No beer for me, unfortunately.

yes, unfortunately. I'd rather have been wrong about this than saving a beer...

**Comment by atgeirr** [comment]
> yeah, sorry: the IQ cache was always conceptualized to be an internal implementation detail by me. maybe it was a mistake to use it directly for the prototype. (it saved a few days/weeks to implement it.)

Now might be a good time to revisit this, before dealing with cache semantics directly becomes too embedded in our codes?

**Comment by andlaus** [comment]
> Now might be a good time to revisit this, before dealing with cache semantics directly becomes too embedded in our codes?

exactly! that's the reason why I'm pushing back on new code that attempts to use the cache directly.

**Comment by atgeirr** [comment]
> exactly! that's the reason why I'm pushing back on new code that attempts to use the cache directly.

I think it is a little unclear what the alternatives are (to me at least), i.e. how to access things without the cache. That may just be my problem though! (We did discuss it in Bergen I think, but not having programmed it much I forget particulars.)

**Comment by andlaus** [comment]
> I think it is a little unclear what the alternatives are

the way I intended it is to iterate over the grid and use element contexts to access the IQs. the IQ-cache becomes transparent in this case.

**Comment by blattms** [comment]
I do not understand what you mean in the second part of the sentence. 

If that is the intended way, why is `cacheIntensiveQuantities` public and why did you let people add code that uses this method in opm-simulators?

**Comment by blattms** [comment]
@atgeirr take a look at [OPM/opm-simulators/e4f8765](/OPM/opm-simulators/pull/1114/commits/e4f876560859178ea6b217eb7b13be652d549cd2) to see what I think @andlaus proposed.

**Comment by andlaus** [comment]
> I do not understand what you mean in the second part of the sentence.

it means that it does not matter anymore if the IQ-cache is used or not or whether an entry is already hot or cold.

> why is cacheIntensiveQuantities public

because if it wasn't, the class that stores them (i.e., the model) would need to befriend *every* single class which potentially accesses them. since -- in principle -- there can an arbitrary number of context classes, that is impossible.

> why did you let people add code that uses this method in opm-simulators?

let me [repeat](https://github.com/OPM/ewoms/issues/163#issuecomment-287920881) myself: When looking back, that was a mistake and I'm certainly not proud of it. Nobody is born perfect, and I my name is certainly not "nobody" ;)

**Comment by blattms** [comment]
Sorry, my mistake. Then I must have mistook you with him/her ;)

**Comment by blattms** [comment]
Over time I get even more surprised. Judging from the code and the values in the matrix in a parallel run it seems like for element centered finite volume ewoms assembles on all elements including ghost and border. So how does the caching work, when is it done and why again is there no caching for overlap/ghost if we assemble there?

**Comment by andlaus** [comment]
modulo bugs, it should work transparently during the linearization. the cache is also supposed to be updated for ghost/overlap entities if there are fluxes to an interior element, i.e. if they exhibit an intersection with the process boundary. the latter is probably the issue which you recently stumbled over; at least if you ran it with more than 2 processes and if my understanding of this is correct there are ghost cells which only share a vertex with the process boundary but that do not have an intersection to an interior element.

did I ever mention that parallel simulations are tricky?

**Comment by andlaus** [comment]
this is not a bug in eWoms as far as I can see...

**Comment by blattms** [comment]
The problem occurs with 2 processes and AFAIK CPGrid does not create any overlap cells with only non-interior neighbors.

**Comment by blattms** [comment]
Also please show where this distinction is done in the code.

**Comment by andlaus** [comment]
not sure what you want. the IQ cache is updated by the element context:

https://github.com/OPM/ewoms/blob/master/ewoms/disc/common/fvbaseelementcontext.hh#L563-L572

I cannot see why this piece of code should be incorrect. can you?

**Comment by andlaus** [comment]
this issue seems to be resolved.
