### ISSUE TITLE
Refactoring of the property system

### ISSUE THREAD

**Issue by andlaus** [OPM/ewoms#167]
The eWoms "property system" serves a very similar purpose as the standard C++ traits mechanism, but it seems to be quite confusing to people who are not familiar with it. IMO it would thus be good to reduce the amount of confusion. The purpose of this issue is to find ways of how this can be done. Please add your comments and suggestions below.

Purpose and Features
==

- The purpose of the eWoms property system is to provide a way to specify compile-time parameters to template classes without having the pass everything explicitly via a template parameter. This is the property (pun intended) which it shares with the standard c++ traits mechanism.
- Compile time. It is possible to use values and types specified via the eWoms property system as template arguments and derive from classes specified via the property system.
- Inheritance. In C++, standard traits classes do not support this:
```c++
#include <iostream>

struct BaseClass {};
struct DerivedClass : public BaseClass {};

template <class T>
struct BaseProperty;

template <class T>
struct DerivedProperty;

template <>
struct BaseProperty<BaseClass> { static constexpr int value = 1; };

template <>
struct DerivedProperty<DerivedClass> { static constexpr int value = 2; };

int main()
{
  std::cout << BaseProperty<DerivedClass>::value;
  return 0;
}
```
produces a compiler error:
```
g++ -std=c++11 bla.cc
bla.cc: In function ‘int main()’:
bla.cc:20:16: error: incomplete type ‘BaseProperty<DerivedClass>’ used in nested name specifier
   std::cout << BaseProperty<DerivedClass>::value;
                ^
```
- Introspection. Using the standards traits mechanism, there is no way to find out which traits are defined for a class. For the eWoms property system, such a list can be printed via `Ewoms::Properties::printValues<TypeTag>();`

Do we need it?
==

If the proposed replacement provides all features mentioned in the previous section, the answer to this question is "no" (and I'll be happy to get rid of it). Unfortunately I'm not aware of anything which is able to do the task.

Proposed refactorings
==

- Rename "property system" to "traits system"
- Rename "type tag" to "traits tag" (or "node tag"?)
- Rename "property tag" to something more descriptive. (suggestions?!)

**Comment by blattms** [comment]
1. I never got why this "derive classes using the properties" is needed. I had to use it in dumux but I never really understood why. Do you have a simple example to illustrate this?
2. I guess your `DerivedProperty` must play an important role. It is not used in your example. Maybe your example is not self-contained?

Otherwise this should do the trick:
```c++
#include <iostream>

struct BaseClass {
  static constexpr int value = 1;
};
struct DerivedClass : public BaseClass {};

template <class T>
struct BaseProperty
{
    static constexpr int value = T::value;
};

int main()
{
    std::cout << BaseProperty<DerivedClass>::value<<std::endl;
    return 0;
}
```
3. I have not used `Ewoms::Properties::printValues<TypeTag>();` very often. It does not help to see where these properties actually get defined, does it? In stl I have concepts like forward iterator, birectional iterator, etc., which kind of inherit from each other also. This is documented in the documentation and somwhen hopefully with C++ concepts.

**Comment by andlaus** [comment]
> Do you have a simple example to illustrate this?

e.g. if you want to set `double` as the standard value for Scalars, but for some simulations you will want to use quadruple precision math. in that case, everything which uses scalars should use it. there are two ways out as far as I can see:

- specify *every* parameter on every hierarchy level. this is next to impossible to maintain and als does not work for the simple reason that not all parameters are known everywhere (or do not even make sense)
- pass everything via template parameters. IMO this does not make things more transparent and it definitely blows up compile time. (hands up who likes the compiler messages when something goes wrong with dune-pdelab code.)

> I guess your DerivedProperty must play an important role. It is not used in your example. Maybe your example is not self-contained?

actually it is not needed in that example. to get a bit more concrete example, you can replace of "BaseClass" by "NewtonMethod", "DerivedClass" by "KrylovNewtonMethod" and "BaseProperty" by e.g. "MaxIteration"

> Otherwise this should do the trick:

yes, but this defines `BaseProperty` for everything and it won't work if you want to change a property for a "middle" hierarchy level.

> I have not used Ewoms::Properties::printValues<TypeTag>(); very often.

this is what's used if you pass `--print-properties=1` to any eWoms test.

> It does not help to see where these properties actually get defined, does it?

it does. it even shows the values of "simple" properties.

> In stl I have concepts like forward iterator, birectional iterator, etc., which kind of inherit from each other also. This is documented in the documentation and somewhen hopefully with C++ concepts.

I don't think these apply in this context.

**Comment by andlaus** [comment]
also remember: patches which replace the property system by something better are welcome. they do not need to be complete but it must be clear how to finish the job.

**Comment by andlaus** [comment]
since this is stale, I'll close it.
