### ISSUE TITLE
Property system in library source files.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/ewoms#218]
I notices that the properties cannot be compiled into the library if there are more then two files doing this. The result is linker errors. Bug or feature?

**Comment by andlaus** [comment]
> Bug or feature?

I consider it to be a bug, but you're welcome to see it as a feature. Anyway, #220 should fix it; it would be nice if you could test-drive that PR.

**Comment by andlaus** [comment]
should be fixed in master. if not, please reopen.
