### ISSUE TITLE
OPM Licence

### ISSUE THREAD

**Issue by mkputul** [OPM/ewoms#250]
Dear All,

I have a question regarding the OPM licencing. I understand that this is not an issue and probably should not be posted here.

Is is allowed to modify the OPM code (for example solvers) for research purposes? 

Thank you.

**Comment by andlaus** [comment]
> Is is allowed to modify the OPM code (for example solvers) for research purposes?

of course. you just need to make sure that you adhere to the license, the short version is that if you provide a compiled version of your modified version, you must be willing to provide the source code to these people. (i.e., binary-only distribution is not allowed.)

**Comment by mkputul** [comment]
Great. Thank you for your response. I appreciate your help.

**Comment by atgeirr** [comment]
The full text of the license is here, if you need to check anything: https://www.gnu.org/licenses/gpl.html

I think @andlaus gave you the most important part. One way to explain the license is that it allows you to:

1. use it for any purpose,
2. modify it in any way,
3. distribute modified or unmodified versions...

... provided that you give those you distribute it to exactly the same rights and conditions.

**Comment by andlaus** [comment]
This seems to be resolved?! I'll close this issue for now.
