### ISSUE TITLE
Black-oil: how to handle fluxes crossing PVT region boundaries

### ISSUE THREAD

**Issue by andlaus** [OPM/ewoms#277]
The black-oil model's current treatment of mass fluxes that  cross PVT region boundaries is incorrect: 

for two PVT regions A and B, imagine that a fluid flux goes from A to B. if the selected quantities to conserve are the "surface volume" of the components, the conserved quantity does not correspond to a quantity that is conserved in the physical world anymore: if the density of e.g. gas at surface conditions is 1 kg/m^3 in region A but 10 kg/m^3 for region B, conserving the "surface volume" of the gas component in the looked uppon case adds 9 kg of gas per cubic meter that flows from region A to region B. obviously this is an extreme example, but the same argument applies for any A and B that exhibit different surface densities.

the interesting question is what can and should be done about this: on one hand, volume fluxes that cross region boundaries could be multiplied by rho_s,B/rho_s,A (this would make sure that mass is conserved), on the other hand, the black-oil model uses pseudo components that consist of a mixture of a multitude of chemical species anyway. This implies that conserving "pseudo component mass" is still incorrect because PVT regions essentially capture different compositions of these pseudo components: e.g., as far as the model is concerned, methane could be converted into butane by simply crossing a PVT region boundary.

**Comment by atgeirr** [comment]
I think that you are correct in your view that this is wrong with the standard black-oil model. There is a fairly common (meaning implemented i multiple different simulators) extension to black-oil called API tracking (not sure what API is short for), which solves exactly the problem you outline by keeping track of (in a simplified way compared to compositional simulation) the composition of the oil in the cells, perhaps we should consider implementing that if there is sufficient interest?

**Comment by andlaus** [comment]
yes, we should probably consider implementing API tracking. it sounds quite elaborate, though...

another possibility would be to abandon black-oil with multiple PVT regions and use a fully compositional model for such cases. Unfortunately that's also very elaborate to implement.

@joakim-hove, @alfbr: do you have any idea if reservoir engineers are aware of above problem?

**Comment by atgeirr** [comment]
> do you have any idea if reservoir engineers are aware of above problem?

I'll add my 2 cents to this as well... I am sure they are, and some are probably abusing the feature to get effects in the simulator they otherwise could not!

**Comment by andlaus** [comment]
I suppose we decided that our approach here is "we don't care". closing.
