### ISSUE TITLE
Development Bounty

### ISSUE THREAD

**Issue by OPMUSER** [OPM/ewoms#337]
Do you think it is a good idea to have a "Development Bounty" on the OPM web site?

As more and more people start to use OPM Flow there will always be "missing" features  compared to the commercial simulator that companies may be prepared to help fund. If there was a "Development Bounty" it may attract additional funding.

Initially, it would probably be best for the developers to list the features they would like to implement to gauge the interest.

Just an idea.

**Comment by andlaus** [comment]
I like the idea, but I think it is better to describe on the website how commercial support for feature development and deployment on customer infrastructure can be bought because I think that OPM is too specialized for development bounties to work.

**Comment by OPMUSER** [comment]
I think that will work just as well, and you could list developments that you would like to do but are not currently funded.

**Comment by andlaus** [comment]
I'm not sure if the github issue tracker for eWoms is the right place for this kind of ideas. Closing for now, but feel free to add further comments.
