### ISSUE TITLE
EclWriter: Do the outputted transmissibilities need values for all cells?

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#374]
In a sequential run ECLWriter seems to use the transmissibilities found in the eclipse file at least this is my interpretation of [this line](/OPM/ewoms/blob/3a03f35acf78b9aa3b3a954a5254a7c3161e1219/ebos/eclwriter.hh#L402). I a parallel run the ones computed in the grid manager in [this line](/OPM/ewoms/blob/3a03f35acf78b9aa3b3a954a5254a7c3161e1219/ebos/eclwriter.hh#L393).

Now the decision on whether to output a transmissibilitx is based on the cartesian index of cells connected by a face  [here](/OPM/ewoms/blob/3a03f35acf78b9aa3b3a954a5254a7c3161e1219/ebos/eclwriter.hh#L404). It is assumed that for two neighboring cells with cartesian index g1 < g2, one of the following conditions holds:
- g2-g1==1
- g2-g1==cartDims[0]
- g2-g1==cartDims[0]*cartDims[1]

That gives rise to the following questions:
1. Are we sure that one of the conditions always holds? What if a cell got merged with its neighbor to satisfy some constraints during grid construction, might the cartesian index not be off by one in this case? 
2. Inactive cells will have transmissibility 0. Is that a problem?

**Comment by andlaus** [comment]
this seems to be stale. if there are any open questions, please feel free to reopen.
