### ISSUE TITLE
Why Does EclProblem::EclProblem(Simulator&) Initialise eclWriter_ Twice?

### ISSUE THREAD

**Issue by bska** [OPM/ewoms#392]
The `EclProblem::EclProblem(Simulator&)` [constructor](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L483) initialises the `eclWriter_` data member twice&mdash;once [in the initialiser list](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L488-L489) and once [in the constructor body](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L496-L498).  Is there a reason for this or is this a result of a previous merge conflict?

**Comment by andlaus** [comment]
that's almost certainly a mistake. #393 fixes it. please merge it if you agree.
