### ISSUE TITLE
Linear solver tolerates non-physical solutions

### ISSUE THREAD

**Issue by rolk** [OPM/ewoms#417]
Symptom: The simulator seems to find a non-physical steady state.

Cause: If the residual in the linear solver is small enough, the initial test for whether the system is already converged in [bicgstabsolver.hh:160](https://github.com/OPM/ewoms/blob/release/2018.10/ewoms/linear/bicgstabsolver.hh#L160) returns true, and no update is done at all to the primary variables. This of course repeats in the next time step, and thus the solution appears to be frozen in time.

The reason for this is that the absolute tolerance, as tested in [combinedcriterion.hh:143](https://github.com/OPM/ewoms/blob/release/2018.10/ewoms/linear/combinedcriterion.hh#L143) is set too high.

This tolerance value is derived from the tolerance at the Newton-iteration level, from the rule-of-thumb at [parallelbicgstabbackend.hh](https://github.com/OPM/ewoms/blob/release/2018.10/ewoms/linear/parallelbicgstabbackend.hh#L126). For some cases (for instance, gravity-driven, two-component, single-phase convection problems) this rule of thumb is insufficient.

A workaround is to set the NewtonRawTolerance property lower.

**Comment by andlaus** [comment]
yes, the tolerances for the linear solver are pretty messy at the moment. It would be great if you could come up with a more stable scheme. maybe we should also force the linear solver to do at least one or two iterations...

**Comment by andlaus** [comment]
looks like this is resolved with the ability to specify the absolute tolerance? if not, feel free to reopen.
