### ISSUE TITLE
Do we actually honor NNC specified in eclipse file

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#419]
I just tried to find out where we query the NNCs specified in the eclipse file in  a run of flow. Surprisingly, the only location that I found is when ebos writes the init file in (`EclWriter::writeInit`). Am I missing something or does this really mean that we do not use/support them currently?

**Comment by atgeirr** [comment]
> adding them would basically boil down to an auxiliary module and a lot of headaches with parallelism.

We should rather add them to the grid as "fake intersections" and hey presto, existing parallel approach handles it nicely.

**Comment by blattms** [comment]
Doesn't the manual state that we support NNC? Was the status different
for flow legacy (at least GeoProps did read and export the NNC from
the exclipse file.

I agree with @atgeirr that we will have no headaches if we incorporate
the NNC into the grid.

**Comment by andlaus** [comment]
You definitely have to hack on the `EclTransmissibilites` class because the geometric properties which are used to calculate the "normal" transmissibilities do not make any sense for NNCs. it is probably not too complicated considering the grand scheme of things, though.

**Comment by andlaus** [comment]
closing his because the discussion has concluded? feel fee to add further comments, though...
