### ISSUE TITLE
test for neglible flow when computing threshold pressures seems wrong

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#437]
IMHO the transmissibility stored by us is already scaled by the face area. Yet the test in [eclthresholdpressure.hh:220 ff.](/OPM/ewoms/blob/118ae279dc77604583740df96f223ae15ed8af71/ebos/eclthresholdpressure.hh#L220-L222) scales it another time with the facearea. This change was added in 8c23c5e3ca of #122.

Is there a special reason for this that I do not see?

**Comment by blattms** [comment]
Still in the code. No opinions?

**Comment by andlaus** [comment]
seems like this issue has been resolved. closing.
