### ISSUE TITLE
EDITNNC Code Potentially Dereferences `end` Iterator

### ISSUE THREAD

**Issue by bska** [OPM/ewoms#448]
The member function `EclTransmissibility<>::applyEditNNC_()` appears to potentially dereference the `end` iterator of a range.  In particular, the following statements appear in the code that handles an `EDITNNC` record between cells that aren't actually [connected](https://github.com/OPM/ewoms/blob/e5a49211b7c2deca7a4284d8272472742175203b/ebos/ecltransmissibility.hh#L577-L579)
```C++
++nnc;
std::ostringstream sstr;
sstr << "Cannot edit NNC from " << nnc->cell1 << " to " << nnc->cell2
```
If `nnc` happens to be "`end - 1`", then advancing the iterator before accessing the elements to print cell ID values will dereference `end`.

I am locally testing the patch below, but I don't know if that is correct in the greater scheme of things.  Any insight is greatly appreciated.

---

```diff
diff --git a/ebos/ecltransmissibility.hh b/ebos/ecltransmissibility.hh
index 6e2e3568..99d98d88 100644
--- a/ebos/ecltransmissibility.hh
+++ b/ebos/ecltransmissibility.hh
@@ -574,11 +574,11 @@ private:
 
             if ( candidate == trans_.end() )
             {
-                ++nnc;
                 std::ostringstream sstr;
-                sstr << "Cannot edit NNC from " << nnc->cell1 << " to " << nnc->cell2
+                sstr << "Cannot edit NNC from " << c1 << " to " << c2
                      << " as it does not exist";
                 Opm::OpmLog::warning(sstr.str());
+                ++nnc;
             }
             else
             {
```

**Comment by blattms** [comment]
Nice catch. This indeed appeared during refactoring in c99b9f3cbd (refactored because do-while seemed frowned on). Obviously my mistake, though. Opened PR #451 with your fix
