### ISSUE TITLE
Updating Reference Solution for SPE1CASE1

### ISSUE THREAD

**Issue by bska** [OPM/ewoms#469]
Commit dfb0647 (PR #461) introduced a new regression test based on the SPE1CASE1 model from opm-tests.  As far as I can tell, there is no automatic way of updating the reference solution&mdash;e.g., in the context of adding new data to the `IWEL` vector&mdash;since this regression test does not plug into the `update_data` request of the Jenkins system.

As of right now that means that said regression test is blocking PR OPM/opm-common#610.  I'd prefer not to disable the test, but I also don't want to take on the responsibility of manually keeping the reference solutions in sync with developments elsewhere.  Can we reach a reasonable compromise here?

**Comment by joakim-hove** [comment]
I don't know the effort required to enable automatic updates, but unless that is simple - or at least forthcoming in readonable time I think the test should be disabled.

**Comment by alfbr** [comment]
We already have a framework for updating reference solutions. My preference is disabling the test until it integrates with the existing framework.

**Comment by andlaus** [comment]
BTW: the effort to update the reference data is quite small and it is not required often:

```bash
cd $EWOMS_BUILD_DIR
make ebos && ctest -R SPE1 -V
cp SPE1* $EWOMS_SRC_DIR/tests/referencesolutions
# make PR
```

**Comment by alfbr** [comment]
I am afraid the test framework you are trying to use does not cater to your use case. Please switch the test off and initiate a dialogue to get a set-up that fits with your goal. Right now you are blocking critical PRs from being merged.

**Comment by atgeirr** [comment]
I agree, the test should be temporarily disabled. I'll make a micro-PR to do that. The only short-term alternative is to disable ewoms tests on Jenkins, which would be a large step backwards.

The test should be done in the same way as the other ones in the first place... When that is done, we'll re-enable the test.

**Comment by andlaus** [comment]
The way to go is to simply disable the validation of the results for all eWoms tests: the all arguments against the SPE1 test raised here equally apply to tests which produce VTK output and I bet the willingness to manually update the VTK reference data is even lower than to update the ECL data. Since I'm busy with more important stuff this week, I'll open a PR to that end at the beginning of next week.
