### ISSUE TITLE
ewoms-compiling problem

### ISSUE THREAD

**Issue by imperial-1** [OPM/ewoms#49]
Dear all,

I have trying to compile evoms after compiling all the OPM and ERE libraries. I have got the following error message: 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find dune-localfunctions (missing: HAVE_DUNE_LOCALFUNCTIONS)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /home/mk812/Downloads/opm-common/cmake/Modules/OpmPackage.cmake:368 (find_package_handle_standard_args)
  /home/mk812/Downloads/opm-common/cmake/Modules/Finddune-localfunctions.cmake:14 (find_opm_package)
  /home/mk812/Downloads/opm-common/cmake/Modules/OpmFind.cmake:147 (find_package)
  /home/mk812/Downloads/opm-common/cmake/Modules/OpmFind.cmake:211 (find_and_append_package_to)
  /home/mk812/Downloads/opm-common/cmake/Modules/OpmLibMain.cmake:104 (find_and_append_package_list_to)
  CMakeLists.txt:106 (include)

Thank you in advance,

Best wishes

**Comment by imperial-1** [comment]
Solution: need to download dune libraries from :
http://www.dune-project.org/download.html

to install dune follow the instructions: 

http://www.dune-project.org/doc/installation-notes.html
                                                               
the version 2.4.1 works fine with OPM.

**Comment by andlaus** [comment]
First of all: welcome to OPM and thanks for the report. It's also nice to see that you managed to fix the issue yourself. (such issues are always the nicest ones from a maintainer's perspective ;))

If you have any further questions, don't hesitate to open new issues or send me private e-mails.

**Comment by imperial-1** [comment]
Thank you very much for your email!!! I will be in contact if I have any question.
